import { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

const demoTalent = [
  { id: 'rina', name: 'Rina Ali', role: 'Interior designer', category: 'Interior', rating: '4.9', image: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=900&q=80', description: 'Warm, modern interiors for residential living and hospitality spaces.' },
  { id: 'malik', name: 'Malik Oseni', role: 'Architectural designer', category: 'Urban', rating: '4.8', image: 'https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=900&q=80', description: 'Concept-led residential and mixed-use developments with a strong urban approach.' },
  { id: 'lina', name: 'Lina Kadi', role: 'Graduate architect', category: 'Residential', rating: '4.7', image: 'https://images.unsplash.com/photo-1511818966892-d7d671e672a2?auto=format&fit=crop&w=900&q=80', description: 'Sustainable residential architecture and thoughtfully detailed spaces.' },
];

const api = async (path, options = {}) => {
  const response = await fetch(path, { credentials: 'include', headers: { 'Content-Type': 'application/json', ...(options.headers || {}) }, ...options });
  const data = response.status === 204 ? null : await response.json();
  if (!response.ok) throw new Error(data?.error || 'Something went wrong.');
  return data;
};

function App() {
  const [page, setPage] = useState(window.location.hash.slice(1) || 'home');
  const [menuOpen, setMenuOpen] = useState(false);
  const [user, setUser] = useState(null);
  const [portfolio, setPortfolio] = useState(null);
  const [notice, setNotice] = useState('');

  useEffect(() => {
    const onHash = () => setPage(window.location.hash.slice(1) || 'home');
    window.addEventListener('hashchange', onHash);
    api('/api/auth/me').then((data) => { setUser(data.user); setPortfolio(data.portfolio); }).catch(() => {});
    return () => window.removeEventListener('hashchange', onHash);
  }, []);

  const go = (next) => { window.location.hash = next; setMenuOpen(false); window.scrollTo({ top: 0, behavior: 'smooth' }); };
  const onAuth = (data) => { setUser(data.user); setPortfolio(data.portfolio || null); go('dashboard'); };
  const logout = async () => { await api('/api/auth/logout', { method: 'POST' }).catch(() => {}); setUser(null); setPortfolio(null); go('home'); };

  return <>
    <Header page={page} user={user} menuOpen={menuOpen} setMenuOpen={setMenuOpen} go={go} logout={logout} />
    {page === 'home' && <Home go={go} />}
    {page === 'login' && <Auth mode="login" onAuth={onAuth} go={go} />}
    {page === 'register' && <Auth mode="register" onAuth={onAuth} go={go} />}
    {page === 'dashboard' && <Dashboard user={user} portfolio={portfolio} go={go} />}
    {page === 'builder' && <Builder user={user} portfolio={portfolio} setPortfolio={setPortfolio} go={go} setNotice={setNotice} />}
    {page === 'marketplace' && <Marketplace setNotice={setNotice} />}
    {notice && <div className="toast" role="status">{notice}<button onClick={() => setNotice('')} aria-label="Dismiss">×</button></div>}
  </>;
}

function Header({ page, user, menuOpen, setMenuOpen, go, logout }) { return <header className="site-header"><div className="nav container">
  <button className="brand" onClick={() => go('home')}><span className="brand-mark">A</span><span>ArchiPortfolio</span></button>
  <nav className={menuOpen ? 'nav-links open' : 'nav-links'} aria-label="Primary"><button className={page === 'home' ? 'active' : ''} onClick={() => go('home')}>Home</button><button className={page === 'builder' ? 'active' : ''} onClick={() => go('builder')}>Builder</button><button className={page === 'marketplace' ? 'active' : ''} onClick={() => go('marketplace')}>Marketplace</button></nav>
  <div className="nav-actions">{user ? <><button className="btn secondary" onClick={() => go('dashboard')}>Dashboard</button><button className="btn primary" onClick={logout}>Log out</button></> : <><button className="btn secondary" onClick={() => go('login')}>Log in</button><button className="btn primary" onClick={() => go('register')}>Start free</button></>}</div>
  <button className="menu-button" onClick={() => setMenuOpen(!menuOpen)} aria-label="Toggle navigation">☰</button>
</div></header>; }

function Home({ go }) { return <main><section className="hero container"><div className="hero-copy"><span className="eyebrow">For students + junior architects</span><h1>Build a portfolio that opens doors.</h1><p className="lead">Create a beautiful portfolio, share your process, and get discovered by people looking for thoughtful design.</p><div className="hero-actions"><button className="btn primary" onClick={() => go('register')}>Create your portfolio <span>→</span></button><button className="btn secondary" onClick={() => go('marketplace')}>Explore talent</button></div><div className="stats"><Stat value="2 min" label="to publish your first project" /><Stat value="100%" label="focused on architecture" /><Stat value="0%" label="commission to get started" /></div></div><div className="hero-visual"><div className="visual-card"><div className="visual-image" /><div className="floating"><span className="tiny">Featured portfolio</span><strong>Maison Courtyard</strong><div className="mini"><span><i className="dot" /> Published</span><span>12 projects</span></div></div></div></div></section>
  <section className="section container"><div className="section-head"><span className="eyebrow">Everything you need</span><h2>Build, showcase, and grow in one place.</h2><p>Skip the blank page and spend more time making work worth sharing.</p></div><div className="feature-grid"><Feature icon="✦" title="A portfolio that feels like you" text="Start with a polished structure, then make every project your own." /><Feature icon="⌁" title="Tell the whole story" text="Show the thinking, drawings, materials, and decisions behind your work." /><Feature icon="↗" title="Get discovered" text="Put your work in front of clients, studios, and collaborators." /></div></section>
  <section className="section container"><div className="section-head"><span className="eyebrow">Made for the work</span><h2>From first sketch to final presentation.</h2></div><div className="showcase"><article className="portfolio-card"><div className="portfolio-preview preview-one" /><div className="portfolio-body"><h3>Material, light, and place</h3><p>Present the details that make your approach distinct.</p><div className="tags"><span className="tag">Residential</span><span className="tag">Process-led</span></div></div></article><article className="portfolio-card"><div className="portfolio-preview preview-two" /><div className="portfolio-body"><h3>Work worth remembering</h3><p>Give every project a clear narrative and a confident finish.</p><div className="tags"><span className="tag">Interior</span><span className="tag">Published</span></div></div></article></div></section>
  <section className="cta-wrap container"><div className="cta-box"><div><span className="eyebrow alt">Start today</span><h2>Turn creativity into opportunity.</h2><p>Your next opportunity could start with the project you already finished.</p></div><div className="cta-actions"><button className="btn primary" onClick={() => go('register')}>Build for free →</button></div></div></section></main>; }
function Stat({ value, label }) { return <div className="stat"><strong>{value}</strong><span>{label}</span></div>; }
function Feature({ icon, title, text }) { return <article className="feature-card"><div className="icon-box">{icon}</div><h3>{title}</h3><p>{text}</p></article>; }

function Auth({ mode, onAuth, go }) { const [form, setForm] = useState({ name: '', email: '', password: '' }); const [error, setError] = useState(''); const register = mode === 'register';
  const submit = async (event) => { event.preventDefault(); setError(''); try { onAuth(await api(register ? '/api/auth/register' : '/api/auth/login', { method: 'POST', body: JSON.stringify(form) })); } catch (e) { setError(e.message); } };
  return <main className="auth-page"><div className="auth-shell"><div className="auth-visual"><div className="auth-overlay"><span className="eyebrow alt">Build your story</span><h1>Bring your design work to the world.</h1><p>Showcase projects, build credibility, and turn your portfolio into real opportunities.</p></div></div><div className="auth-card"><button className="brand" onClick={() => go('home')}><span className="brand-mark">A</span><span>ArchiPortfolio</span></button><h2>{register ? 'Create your account' : 'Welcome back'}</h2><p className="muted">{register ? 'Your best work deserves a home.' : 'Pick up where you left off.'}</p>{error && <div className="form-error" role="alert">{error}</div>}<form className="auth-form" onSubmit={submit}>{register && <label>Name<input required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} placeholder="Your name" /></label>}<label>Email address<input required type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} placeholder="name@studio.com" /></label><label>Password<input required minLength="8" type="password" value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} placeholder="At least 8 characters" /></label><button className="btn primary full-width">{register ? 'Create account' : 'Sign in'}</button></form><p className="switch">{register ? 'Already have an account?' : 'New to ArchiPortfolio?'} <button onClick={() => go(register ? 'login' : 'register')}>{register ? 'Sign in' : 'Create one'}</button></p></div></div></main>; }

function Dashboard({ user, portfolio, go }) { if (!user) return <EmptyState title="Your workspace is waiting." text="Sign in to manage your portfolio and projects." action="Log in" onClick={() => go('login')} />; const projects = portfolio?.projects || []; return <main className="app-page container"><div className="page-header"><div><span className="eyebrow">Dashboard</span><h1>Good morning, {user.name.split(' ')[0]}.</h1><p className="muted">Here is what is happening with your portfolio.</p></div><button className="btn primary" onClick={() => go('builder')}>Add project →</button></div><div className="stats-row"><div className="mini-card"><span>Projects</span><strong>{projects.length}</strong><small>in your portfolio</small></div><div className="mini-card"><span>Status</span><strong>{portfolio?.published ? 'Live' : 'Draft'}</strong><small>{portfolio?.published ? 'visible in marketplace' : 'publish when ready'}</small></div><div className="mini-card"><span>Profile</span><strong>{user.bio ? 'Ready' : '60%'}</strong><small>{user.bio ? 'complete' : 'add a short bio'}</small></div></div><section className="panel"><div className="panel-head"><h2>Recent projects</h2><button className="btn secondary small-btn" onClick={() => go('builder')}>Manage</button></div>{projects.length ? <div className="project-list">{projects.map((project) => <div className="project-item" key={project.id}><div className="project-thumb" style={{ backgroundImage: `url(${project.coverUrl || 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=600&q=80'})` }} /><div><strong>{project.title}</strong><small>{project.category} {project.year ? `· ${project.year}` : ''}</small></div><span className={`status ${project.published ? 'good' : 'neutral'}`}>{project.published ? 'Live' : 'Draft'}</span></div>)}</div> : <EmptyState title="No projects yet" text="Add your first project to start shaping your portfolio." action="Open builder" onClick={() => go('builder')} />}</section></main>; }

function Builder({ user, portfolio, setPortfolio, go, setNotice }) { const [form, setForm] = useState({ title: '', category: 'Residential', summary: '', year: new Date().getFullYear(), coverUrl: '', published: false }); const [saving, setSaving] = useState(false); if (!user) return <EmptyState title="Create your workspace first." text="Sign in to use the portfolio builder." action="Log in" onClick={() => go('login')} />;
  const update = (key, value) => setForm((old) => ({ ...old, [key]: value }));
  const save = async (event) => { event.preventDefault(); setSaving(true); try { const project = await api('/api/projects', { method: 'POST', body: JSON.stringify({ ...form, year: Number(form.year) || null }) }); setPortfolio({ ...portfolio, projects: [project, ...(portfolio?.projects || [])] }); setForm({ title: '', category: 'Residential', summary: '', year: new Date().getFullYear(), coverUrl: '', published: false }); setNotice('Project saved to your portfolio.'); } catch (e) { setNotice(e.message); } finally { setSaving(false); } };
  return <main className="app-page container"><div className="page-header"><div><span className="eyebrow">Portfolio builder</span><h1>Make your work unmistakable.</h1><p className="muted">Add a project and see it appear in your portfolio.</p></div><button className="btn secondary" onClick={() => go('dashboard')}>Back to dashboard</button></div><div className="builder-grid"><form className="panel form-stack" onSubmit={save}><h2>New project</h2><label>Project title<input required value={form.title} onChange={(e) => update('title', e.target.value)} placeholder="e.g. Maison Courtyard" /></label><label>Category<select value={form.category} onChange={(e) => update('category', e.target.value)}><option>Residential</option><option>Interior</option><option>Urban</option><option>Commercial</option><option>Landscape</option></select></label><div className="two-col"><label>Year<input type="number" value={form.year} onChange={(e) => update('year', e.target.value)} /></label><label>Cover image URL<input type="url" value={form.coverUrl} onChange={(e) => update('coverUrl', e.target.value)} placeholder="https://…" /></label></div><label>Project summary<textarea required rows="6" value={form.summary} onChange={(e) => update('summary', e.target.value)} placeholder="What should people understand about this project?" /></label><label className="checkbox-row"><input type="checkbox" checked={form.published} onChange={(e) => update('published', e.target.checked)} /> Publish immediately</label><button className="btn primary" disabled={saving}>{saving ? 'Saving…' : 'Save project'}</button></form><section className="panel preview-panel"><div className="panel-head"><h2>Live preview</h2><span className="chip">Preview</span></div><article className="portfolio-preview-card"><div className="preview-hero" style={form.coverUrl ? { backgroundImage: `url(${form.coverUrl})` } : undefined} /><div className="preview-body"><span className="faux-tag">{form.category}</span><h3>{form.title || 'Your project title'}</h3><p>{form.summary || 'A clear summary will help visitors understand the idea, context, and craft behind your work.'}</p><div className="preview-meta"><span>{form.year}</span><span>Architecture</span></div></div></article></section></div></main>; }

function Marketplace({ setNotice }) { const [filter, setFilter] = useState('All'); const [talent, setTalent] = useState(demoTalent); const [selected, setSelected] = useState(null); useEffect(() => { api('/api/marketplace').then((data) => { if (data.length) setTalent(data.map((person, index) => ({ ...person, id: person.id || index, image: person.image || demoTalent[index % demoTalent.length].image }))); }).catch(() => {}); }, []); const categories = ['All', 'Interior', 'Residential', 'Urban', 'Commercial']; const filtered = useMemo(() => filter === 'All' ? talent : talent.filter((person) => person.category === filter), [filter, talent]); return <main className="app-page container"><div className="page-header"><div><span className="eyebrow">Marketplace</span><h1>Find design talent that fits your brief.</h1><p className="muted">Explore portfolios from emerging designers and architects.</p></div></div><div className="filter-bar">{categories.map((category) => <button className={filter === category ? 'filter active' : 'filter'} key={category} onClick={() => setFilter(category)}>{category}</button>)}</div><div className="card-grid">{filtered.map((person) => <article className="market-card" key={person.id}><div className="market-thumb" style={{ backgroundImage: `url(${person.image})` }} /><div className="market-info"><div className="market-head"><div><h2>{person.name}</h2><span>{person.role}</span></div><span className="rating">★ {person.rating}</span></div><p>{person.description}</p><div className="market-tags"><span>{person.category}</span><span>Available</span></div><button className="btn secondary small-btn" onClick={() => setSelected(person)}>View profile</button></div></article>)}</div>{selected && <div className="modal-backdrop" onClick={() => setSelected(null)}><div className="modal" onClick={(e) => e.stopPropagation()}><button className="modal-close" onClick={() => setSelected(null)}>×</button><span className="eyebrow">{selected.category}</span><h2>{selected.name}</h2><p className="muted">{selected.role}</p><p>{selected.description}</p><button className="btn primary" onClick={() => { setSelected(null); setNotice('Tell us about your project and we will connect you.'); }}>Start an inquiry →</button></div></div>}</main>; }
function EmptyState({ title, text, action, onClick }) { return <div className="empty-state"><h2>{title}</h2><p className="muted">{text}</p>{action && <button className="btn primary" onClick={onClick}>{action}</button>}</div>; }

createRoot(document.getElementById('root')).render(<App />);
